In [1]:
import numpy as np
import torch
from torch import nn
from tropical import to_tensor, Tropical, TropicalMonomial, TropicalPolynomial, PolyNet, DiffPolyNet

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
x = np.random.randint(20,size=3)
x_t = to_tensor(x)

Let' create test polynomials

In [4]:
a = TropicalPolynomial([[1.2345,3,2,1],[1.2345,2,7,1],[1.2345,0,9,1],
                        [1.2345,10,19,1]])

b = TropicalPolynomial([[1.2345,2,3,1],[2.3456,3,4,1]])

In [5]:
a.evaluate(x), b.evaluate(x)

(212.2345, 58.345600000000005)

Convert each polynomial to net

In [11]:
a_net = PolyNet(a)
b_net = PolyNet(b)

In [12]:
a_net

PolyNet(
  (linears): ModuleList(
    (0): Linear(in_features=3, out_features=6, bias=True)
    (1): Linear(in_features=6, out_features=3, bias=True)
    (2): Linear(in_features=3, out_features=1, bias=True)
  )
)

In [16]:
b_net

PolyNet(
  (linears): ModuleList(
    (0): Linear(in_features=3, out_features=3, bias=True)
    (1): Linear(in_features=3, out_features=1, bias=True)
  )
)

In [17]:
a_net.forward(x_t), b_net.forward(x_t)

(tensor([212.2345], grad_fn=<AddBackward0>),
 tensor([58.3456], grad_fn=<AddBackward0>))

Values converge!

Let's look at the difference of these polynomials

In [73]:
a.evaluate(x)/b.evaluate(x)

86.88889999999999

In [74]:
a_net.forward(x_t)-b_net.forward(x_t)

tensor([86.8889], grad_fn=<SubBackward0>)

Create a network for the difference

In [75]:
net = DiffPolyNet(a,b)

In [76]:
net

DiffPolyNet(
  (net): Sequential(
    (0): Linear(in_features=6, out_features=9, bias=True)
    (1): ReLU()
    (2): Linear(in_features=9, out_features=4, bias=True)
    (3): ReLU()
    (4): Linear(in_features=4, out_features=1, bias=True)
  )
)

In [77]:
net.forward(x_t)

tensor([86.8889], grad_fn=<AddBackward0>)